version: "3.9"

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - 3333:3333
    command: /bin/sh -c "npm install && npm run start"

  db:
    image: postgres:14.5-alpine3.16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seek

volumes:
  db-data: ~
