# this file is to simulate running the production application
version: "3.9"

services:
  app:
    depends_on:
      - db
    image: seek:latest
    ports:
      - 3333:3333
    environment:
      DB_NAME: seek
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password

  db:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seek

volumes:
  db-data: ~
